### ISSUE TITLE
Create a function that prints the bear form to the dom

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#10]
### User Story
---
when a user visits the site they should see a styled form that accepts data from a bear of their choosing. It should accept a bear name and a image url of the bear.

### AC
---
A form should be built through a printToDom function and it should display to the dom. The form should be styled and be presentable to the viewer. code should be properly indented and east to read. code should be stored in its own module.

### Dev Notes
---
**To-Do**

- [x] Create a module that will house the printToDom function that will build the form

- [x] Import the printToDom function into the module

- [x] Create the formBuilding function using a form from bootstrap

- [x] Make a click event that will be tied to the submit button and should run the cardBuilding function when clicked

- [x] Export the function to be used in the main.js and placed in the init function

### Moqup

![](https://user-images.githubusercontent.com/62913995/83084633-231a2d00-a04f-11ea-8e75-69207612a13a.png)
