### ISSUE TITLE
Create a print to dom function

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#12]
### User Story
---
When a dev views the code they should see a utils.js module and in the module they should see a function that will print to dom when ran through another function

### AC
---
There should be a module that will house the printToDom function. in that module should be a clean and properly indented function that shows the printToDom function. the function should be exported for use in other modules

### Dev Notes
---

**To-Do**

- [x] Create a module named utils.js

- [x] In the module build the printToDom function

- [x] Export the function so it may be used in other modules

**Sample Code**

` const printToDom = (selector, textToPrint) => {
     const selectedDiv = document.querySelector(selector);
     selectedDiv.innerHTML = textToPrint;
}

export default { printToDom } `
