### ISSUE TITLE
Create bootstrap form

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#2]
### User Story
as a developer i should see a bootstrap form that is properly formatted within a function that prints to the dom.

### AC
**When** the developer opens the form.js file
**They** should see a function that prints to the dom
**And** that function should be building a domString containing the bootstrap form
**And** when tested the form should populate on the page

### Dev Notes

**To-Do**

- [ ] Create a container for printToDom function to target

- [ ] Create a function that prints to the dom

- [ ]  Place the bootstrap form into the function so it gets add to a domString and print to the page

![form moqup](https://user-images.githubusercontent.com/62913995/83084633-231a2d00-a04f-11ea-8e75-69207612a13a.png)
