### ISSUE TITLE
Design cards from bootstrap that are made when bears are put in

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#3]
### User Story
When the user inputs their bear info into the form and click the button. A new bear should be printed to the dom in their own card.

### AC
**When** the user visits the should they should be able to input a bear into a form.
**And** they should be able to click a button to submit a bear of their choosing
**And** when they click the button a card should populate using the information they had provided on the form

### Dev Notes

**To-Do**

- [ ] create a container for cardToDom function to target

- [ ] create a function that prints the card to the page when the button is clicked

- [ ] take a bootstrap card and place in function that adds tot he domString

![bear-card](https://user-images.githubusercontent.com/62913995/83085160-c3248600-a050-11ea-8b11-8a6c9046f02b.png)
