### ISSUE TITLE
style form & cards

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#4]
### User Story
---
When the user visits the page they should see a styled form with colors and different fonts. They should also when submitting their info on their bear of choice into the form a styled card should populate the dom using the same color scheme and fonts.

### AC
---
**When** a user visits the page they should see a styled form
**And** when information is submitted in the form a styled card should populate

### Dev Notes
---

**To-Do**

- [x] Choose a color palette and attach below

- [x] Choose two fonts and attach below as well as link into code

- [x] Utilize the color palette to change font, border, and button colors

- [x] Utilize the fonts attached below to discern from headings and normal text

---
**Coloring**
![Bear Watcher colors](https://user-images.githubusercontent.com/62913995/83085877-d0db0b00-a052-11ea-9158-88dd21e6a4d0.png)
---
**Fonts**
Balsamiq Sans
https://fonts.google.com/specimen/Balsamiq+Sans?sidebar.open&selection.family=Balsamiq+Sans
![first font](https://user-images.githubusercontent.com/62913995/83086020-362efc00-a053-11ea-987b-fd60880a521b.png)

Libre Baskerville
https://fonts.google.com/specimen/Libre+Baskerville?sidebar.open&selection.family=Balsamiq+Sans|Libre+Baskerville
![second font](https://user-images.githubusercontent.com/62913995/83086094-6d051200-a053-11ea-8771-d657e0b7e7ac.png)
