### ISSUE TITLE
Create a module and function that will build cards and print to the dom on a click event

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/bear-watcher#5]
### User Story
---
As a developer i should see code in it's respective module that is a function that creates a dom string that makes a card. This function should be tied to a click event that runs when information is put into the bear form and submitted.

### AC
---
**The**  dev should be able to open the module labled card.js and see clean structured code
**And**
**And**  they should be able to read clearly the function that builds the card
**And**  they should see where the function is attached to a click event
**And** finally should be able to see where the function has been exported and see where it has been imported into other modules

### Dev Notes
---

**To-Do**

- [x] Create a module that will house the cardBuilding function.

- [x] Import printToDom function to the module

- [x] Create the card building function utilizing the printToDom function

- [x] Insert data from the bears array so the data from it is used when the card is built

- [x] Export the function so it can be attached to a click event that will be tied to the printToDom function that is used to build the form.

### Moqup

![](https://user-images.githubusercontent.com/62913995/83085160-c3248600-a050-11ea-8b11-8a6c9046f02b.png)
